-- function spawn_altar_top() end
-- function spawn_endportal() end
-- function spawn_portal() end
-- function spawn_tele1() end
-- function spawn_tele2() end
-- function spawn_tele3() end
-- function spawn_tele4() end
-- function spawn_tele5() end
-- function spawn_tele6() end
function load_acidtank_left() end
function load_acidtank_right() end
function load_altar() end
function load_background_panel_big() end
function load_background_scene() end
function load_beam() end
function load_building_stash() end
function load_bunk_with_surprise() end
function load_catwalk() end
function load_cavein() end
function load_chamfer_bottom_l() end
function load_chamfer_bottom_r() end
function load_chamfer_inner_bottom_l() end
function load_chamfer_inner_bottom_r() end
function load_chamfer_inner_top_l() end
function load_chamfer_inner_top_r() end
function load_chamfer_top_l() end
function load_chamfer_top_r() end
function load_floor_rubble_l() end
function load_floor_rubble_r() end
function load_floor_rubble() end
function load_furniture_bunk() end
function load_furniture() end
function load_gold_entity() end
function load_gunpowderpool_01() end
function load_gunpowderpool_02() end
function load_gunpowderpool_03() end
function load_gunpowderpool_04() end
function load_i_structures() end
function load_large_structures() end
function load_oiltank_alt() end
function load_oiltank() end
function load_panel_01() end
function load_panel_02() end
function load_panel_03() end
function load_panel_04() end
function load_panel_05() end
function load_panel_06() end
function load_panel_07() end
function load_panel_08() end
function load_panel_09() end
function load_paneling() end
function load_pillar_base() end
function load_pillar_filler_tall() end
function load_pillar_filler() end
function load_pillar() end
function load_pixel_scene_alt() end
function load_pixel_scene_tall() end
function load_pixel_scene_wide() end
function load_pixel_scene() end
function load_pixel_scene2() end
function load_pixel_scene3() end
function load_pixel_scene4_alt() end
function load_pixel_scene4() end
function load_pixel_scene5() end
function load_pixel_scene5b() end
function load_pod_large() end
function load_pod_small_l() end
function load_pod_small_r() end
function load_puzzle_capsule_b() end
function load_puzzle_capsule() end
function load_puzzleroom() end
function load_random_background_sprite() end
function load_random_pixel_scene() end
function load_small_background_scene() end
function load_structures() end
function load_suspension_bridge() end
function load_verlet_rope_with_one_joint() end
function load_verlet_rope_with_two_joints() end
function load_warning_strip() end
function random_layout() end
function spawn_aabb() end
function spawn_acid() end
function spawn_alchemist() end
function spawn_all_perks() end
function spawn_all_shopitems() end
function spawn_altar_torch() end
function spawn_any_enemy() end
function spawn_apparatus() end
function spawn_apparition() end
function spawn_areachecks_left() end
function spawn_areachecks_right() end
function spawn_areachecks() end
function spawn_barrels() end
function spawn_barricade() end
function spawn_bbqbox() end
function spawn_beam_low_flipped() end
function spawn_beam_low() end
function spawn_beam_steep_flipped() end
function spawn_beam_steep() end
function spawn_big_bushes() end
function spawn_big_enemies() end
function spawn_bigfish() end
function spawn_bigtorch() end
function spawn_blood() end
function spawn_bones() end
function spawn_book() end
function spawn_boss_dragon() end
function spawn_boss_limbs_trigger() end
function spawn_boss_limbs() end
function spawn_boss_music_and_statues() end
function spawn_bottle() end
function spawn_bridge() end
function spawn_brimstone() end
function spawn_bunker() end
function spawn_bunker2() end
function spawn_buried_eye_teleporter() end
function spawn_burning_barrel() end
function spawn_candles() end
function spawn_chair() end
function spawn_cheap_shopitem() end
function spawn_check1() end
function spawn_check2() end
function spawn_check3() end
function spawn_checkpoint_1() end
function spawn_checkpoint_2() end
function spawn_chest() end
function spawn_cloud_trap() end
function spawn_collapse() end
function spawn_control_workshop() end
function spawn_cook() end
function spawn_corpse() end
function spawn_crate() end
function spawn_crawlers() end
function spawn_cyst() end
function spawn_debug_mark() end
function spawn_doors() end
function spawn_dragonspot() end
function spawn_drill_laser() end
function spawn_duplicator() end
function spawn_egg() end
function spawn_electricity_trap() end
function spawn_end_portal() end
function spawn_endcrystal() end

function spawn_essence() end
function spawn_f_trigger() end
function spawn_f() end
function spawn_finish_line() end
function spawn_fish() end
function spawn_forcefield_generator() end
function spawn_forge_check() end
function spawn_friend() end
function spawn_from_list() end
function spawn_fruit() end
function spawn_fullhp() end
function spawn_fun() end
function spawn_fungi() end
function spawn_fungitrap() end
function spawn_gate() end
function spawn_ghost_crystal() end
function spawn_ghost() end
function spawn_ghostlamp() end
function spawn_grass() end
function spawn_group() end
function spawn_hanger() end
function spawn_hanging_prop() end
function spawn_heart() end
function spawn_hourglass_blood() end
function spawn_hourglass_master() end
function spawn_hourglass_music_trigger() end
function spawn_hp_mult() end
function spawn_hp() end
function spawn_huussi_checker() end
function spawn_i_trigger() end
function spawn_i() end
function spawn_inventory_trigger() end
function spawn_inventory() end
function spawn_items() end
function spawn_killer() end
function spawn_lab_puzzle() end
function spawn_ladder() end
function spawn_lamp_long() end
function spawn_lamp() end
function spawn_lamp2() end
function spawn_large_enemies() end
function spawn_laser_trap() end
function spawn_lasergate_ver() end
function spawn_lasergun() end
function spawn_leggy() end
function spawn_lukki() end
function spawn_machines() end
function spawn_material_checker() end
function spawn_meditation_cube() end
function spawn_metportal() end
function spawn_mimic_sign() end
function spawn_moon() end
function spawn_motordoor() end
function spawn_mouse_trigger() end
function spawn_mouse() end
function spawn_mouth() end
function spawn_music_machine() end
function spawn_music_trigger() end
function spawn_nest() end
function spawn_ocarina() end
function spawn_oiltank_puzzle() end
function spawn_orb() end
function spawn_perk_reroll() end
function spawn_perk() end
function spawn_persistent_teleport() end
function spawn_physics_acid_fungus() end
function spawn_physics_fungus() end
function spawn_physicsstructure() end
function spawn_pillars() end
function spawn_pipes_big_hor() end
function spawn_pipes_big_turn_left() end
function spawn_pipes_big_turn_right() end
function spawn_pipes_big_ver() end
function spawn_pipes_cross() end
function spawn_pipes_hor() end
function spawn_pipes_turn_left() end
function spawn_pipes_turn_right() end
function spawn_pipes_ver() end
function spawn_potion_altar() end
function spawn_potions() end
function spawn_pressureplate() end
function spawn_pressureplates() end
function spawn_prize() end
function spawn_props() end
function spawn_props2() end
function spawn_props3() end
function spawn_props4() end
function spawn_racing_cart() end
function spawn_rainbow_card() end
function spawn_receptacle_oil() end
function spawn_receptacle() end
function spawn_reward_wands() end
function spawn_robots() end
function spawn_rock() end
function spawn_rock1() end
function spawn_rock2() end
function spawn_root_grower() end
function spawn_rubble() end
function spawn_runes() end
function spawn_sampo_spot() end
function spawn_save() end
function spawn_scavenger_party() end
function spawn_scavengers() end
function spawn_scorpions() end
function spawn_secret_checker() end
function spawn_secret() end
function spawn_shopitem() end
function spawn_shopkeeper() end
function spawn_skulls() end
function spawn_small_animals() end
function spawn_small_enemies() end
function spawn_specialshop() end
function spawn_spell_visualizer() end
function spawn_spirit_spawner() end
function spawn_stains_ceiling() end
function spawn_stains() end
function spawn_stash() end
function spawn_statue_back() end
function spawn_statue_hand() end
function spawn_statue() end
function spawn_statues() end
function spawn_stones() end
function spawn_stopwatches() end
function spawn_swing_puzzle_box() end
function spawn_swing_puzzle_target() end
function spawn_table() end
function spawn_target() end
function spawn_teleport_back() end
function spawn_teleport() end
function spawn_teleporter() end
function spawn_tower_short() end
function spawn_tower_tall() end
function spawn_trapwand() end
function spawn_treasure() end
function spawn_tree() end
function spawn_trees() end
function spawn_trigger_check_stats_reference() end
function spawn_trigger_check_stats() end
function spawn_turret() end
function spawn_unique_enemy() end
function spawn_unique_enemy2() end
function spawn_unique_enemy3() end
function spawn_vasta_or_vihta() end
function spawn_vines_b() end
function spawn_vines() end
function spawn_wand_trap_electricity_source() end
function spawn_wand_trap_electricity() end
function spawn_wand_trap_ignite() end
function spawn_wand_trap() end
function spawn_wand() end
function spawn_wands() end
function spawn_wasd_trigger() end
function spawn_wasd() end
function spawn_waterspout() end
function spawn_wheel_small() end
function spawn_wheel_tiny() end
function spawn_wheel() end
function spawn_with_limited_random() end
function spawn_workshop_extra() end
function spawn_workshop() end
function spawn_worm_deflector() end
function spawn_worm() end
